// Generated by wxt
export {}
declare global {
  const ALARMS: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/constants')['ALARMS']
  const BlockIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['BlockIcon']
  const CheckIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['CheckIcon']
  const ClearIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['ClearIcon']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const DEFAULTS: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/constants')['DEFAULTS']
  const DISABLE_TIMERS: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/constants')['DISABLE_TIMERS']
  const DomainIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['DomainIcon']
  const ENDPOINTS: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/constants')['ENDPOINTS']
  const EXTENSION_ENTROPY: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/constants')['EXTENSION_ENTROPY']
  const ErrorIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['ErrorIcon']
  const ExternalLinkIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['ExternalLinkIcon']
  const GlobeIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['GlobeIcon']
  const InfoIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['InfoIcon']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const RefreshIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['RefreshIcon']
  const STORAGE_KEYS: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/constants')['STORAGE_KEYS']
  const SearchAllIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['SearchAllIcon']
  const SearchIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['SearchIcon']
  const SettingsIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['SettingsIcon']
  const SpinnerIcon: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/icons')['SpinnerIcon']
  const browser: typeof import('wxt/browser')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const formatNumber: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/utils')['formatNumber']
  const injectScript: typeof import('wxt/client')['injectScript']
  const isQueryBlocked: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/utils')['isQueryBlocked']
  const isSameSite: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/utils')['isSameSite']
  const sendMessage: typeof import('/home/rooki/autoclaudeprojects/pisentinel/utils/messaging')['sendMessage']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { MessageType, AuthenticatePayload, SetBlockingPayload, DomainPayload, GetQueriesPayload, SaveConfigPayload, TestConnectionPayload, MessageResponse, Message, SerializableTabDomains, AuthenticateResponse, GetStateResponse, GetStatsResponse, GetBlockingStatusResponse, SetBlockingResponse, GetTabDomainsResponse, GetQueriesResponse, DomainActionResponse, SearchDomainResponse } from '/home/rooki/autoclaudeprojects/pisentinel/utils/messaging'
  import('/home/rooki/autoclaudeprojects/pisentinel/utils/messaging')
  // @ts-ignore
  export type { AuthResponse, StatsSummary, BlockingStatus, QueryEntry, DomainEntry, ApiError, ExtensionState, TabDomainData, PersistedConfig, EncryptedData, SessionData } from '/home/rooki/autoclaudeprojects/pisentinel/utils/types'
  import('/home/rooki/autoclaudeprojects/pisentinel/utils/types')
}
